### ISSUE TITLE
barrage.py 94行，string()函数条件判断错误

### ISSUE THREAD

**Issue by Arcadia822** [py-wuhao/ks_barrage#1]
commit: e7498d26d9b4a40f430e68caa59340ca17bf2167

[barrage.py](https://github.com/py-wuhao/ks_barrage/blob/e7498d26d9b4a40f430e68caa59340ca17bf2167/barrage.py) 第94行

此处条件判断误写，可能导致文本解码出错或抛出异常
```python
elif r < 191 < 224
```

应为：

```python
elif 191 < r < 224
```

**Comment by py-wuhao** [comment]
好的，已更正

**Comment by 18539663587** [comment]
大佬 有问题请教
