### ISSUE TITLE
是不是不能用了

### ISSUE THREAD

**Issue by MaNongXiaoGang** [py-wuhao/ks_barrage#12]

**Comment by py-wuhao** [comment]
是的，建立连接要传cookie 是条件之一

**Comment by MaNongXiaoGang** [comment]
有个问题想请教，我获取token是在https://live.kuaishou.com/m_graphql 获取的，还有服务器地址。 可是我把这些值替换你代码的就报错。  而你的代码可以用。  我要怎么才能获取更多的token

**Comment by py-wuhao** [comment]
浏览器无痕模式  手动复制

**Comment by sbitpdc** [comment]
> 浏览器无痕模式 手动复制

按照人的无痕模式也请求不了

**Comment by sbitpdc** [comment]
> 浏览器无痕模式 手动复制

我的python版本是3.8，websocket-client库，我在ubuntu 试了，运行不成功

**Comment by kachacha** [comment]
`
Connection is already closed.
### closed ###
`
`page_id` 解析方式有变化吗？我推的 js 好像跟你的不一样。

**Comment by kachacha** [comment]
`demo.py` -> 58行

``error from callback <function on_open at 0x000001B65003FE58>: a bytes-like object is required, not 'list'``

**Comment by py-wuhao** [comment]
> > 浏览器无痕模式手动复制
> 
> 我的python版本是3.8，websocket-client库，我在ubuntu试了，运行不成功

具体是运行不成功的现象是什么

**Comment by py-wuhao** [comment]
> `demo.py` -> 58行
> 
> `error from callback <function on_open at 0x000001B65003FE58>: a bytes-like object is required, not 'list'`

![image](https://user-images.githubusercontent.com/43025911/85406838-f2b5a800-b594-11ea-95b0-55a0759834de.png)
ws.send(d,***)吗？d就是一个整型列表，你确定下使用的是 websocket-client

**Comment by py-wuhao** [comment]
> `
> Connection is already closed.
> 
> ### closed
> ` `page_id` 解析方式有变化吗？我推的 js 好像跟你的不一样。

page_id  并没有验证，我使用的随机字符串

**Comment by kachacha** [comment]
> > `
> > Connection is already closed.
> > ### closed
> > ` `page_id` 解析方式有变化吗？我推的 js 好像跟你的不一样。
> 
> page_id 并没有验证，我使用的随机字符串

是的，这边测试通过了，在你给出代码的 57 行修改了一些：`self.send(bytearray(d), websocket.ABNF.OPCODE_BINARY)`

这样才能够正确的传入其参数类型。

输出后的结果中有报错的记录~

![](https://cdn.jsdelivr.net/gh/kachacha/markdownPicture/docImg/Snipaste_2020-06-23_22-02-33.png)

**Comment by kachacha** [comment]
![Snipaste_2020](https://cdn.jsdelivr.net/gh/kachacha/markdownPicture/docImg/Snipaste_2020-06-23_22-02-33.png)
https://cdn.jsdelivr.net/gh/kachacha/markdownPicture/docImg/Snipaste_2020-06-23_22-02-33.png

**Comment by kachacha** [comment]
[](https://cdn.jsdelivr.net/gh/kachacha/markdownPicture/docImg/Snipaste_2020-06-23_22-02-33.png)

**Comment by py-wuhao** [comment]
![image](https://user-images.githubusercontent.com/43025911/85415851-5f826f80-b5a0-11ea-8583-4ac085c0517b.png)

**Comment by py-wuhao** [comment]
> ![Snipaste_2020](https://camo.githubusercontent.com/556b6f68e1fe311ca32c8d8bb262c66266302ffa/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6b616368616368612f6d61726b646f776e506963747572652f646f63496d672f536e6970617374655f323032302d30362d32335f32322d30322d33332e706e67)
> https://cdn.jsdelivr.net/gh/kachacha/markdownPicture/docImg/Snipaste_2020-06-23_22-02-33.png



> ![Snipaste_2020](https://camo.githubusercontent.com/556b6f68e1fe311ca32c8d8bb262c66266302ffa/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6b616368616368612f6d61726b646f776e506963747572652f646f63496d672f536e6970617374655f323032302d30362d32335f32322d30322d33332e706e67)
> https://cdn.jsdelivr.net/gh/kachacha/markdownPicture/docImg/Snipaste_2020-06-23_22-02-33.png
那你把发心跳包也加上

**Comment by py-wuhao** [comment]
![image](https://user-images.githubusercontent.com/43025911/85416205-c30c9d00-b5a0-11ea-91d9-95c1b44ae956.png)

**Comment by py-wuhao** [comment]
<img width="1116" alt="微信截图_20200623222848" src="https://user-images.githubusercontent.com/43025911/85416404-00712a80-b5a1-11ea-8b80-99aaef70474f.png">

**Comment by kachacha** [comment]
我安装的是: `websocket-client~=0.57.0`
![](https://cdn.jsdelivr.net/gh/kachacha/markdownPicture/docImg/Snipaste_2020-06-23_22-32-50.png)

总之已经解决了，非常感谢~

**Comment by kachacha** [comment]
现在在研究抖音的直播弹幕如何获取 @py-wuhao
