### ISSUE TITLE
Token, stream_id, page_id获取

### ISSUE THREAD

**Issue by Arcadia822** [py-wuhao/ks_barrage#3]
今天测试了一下，接口可能有调整，目前token和page_id都要按ws初始包抓到的内容来填才能正确连接

直播间查看源代码可以拿到stream_id
手动获取token和page_id可以接通，在代码里有没有获取方案呢？

小弟初学爬虫，如果是很stupid的问题，抱歉啦/抱拳

**Comment by Arcadia822** [comment]
通过selenium模拟打开直播间，监听ws发包应该是可行的，就是有点麻烦。。。

**Comment by py-wuhao** [comment]
刚刚测试了下目前代码只替换stream_id正常爬取

**Comment by Arcadia822** [comment]
是我的实现有误，打扰了😰
